name: flutter_web_auth_2_root

publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  - flutter_web_auth_2
  - flutter_web_auth_2/example
  - flutter_web_auth_2_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  melos: ^7.0.0-dev.7
